### ISSUE TITLE
Project is dead?

### ISSUE THREAD

**Issue by plmuninn** [milliondreams/socket.io.play#15]
??

**Comment by milliondreams** [comment]
I haven't been using it personally for quite sometime now... 
And haven't got any feedback or feature requests or bugs ever... so I am assuming people are not using it either... or they are using it with there own changes...

So doesn't make sense for me to spend time on this unless and until I get a new requirement for this... So won't say dead, but dormant/deep hibernating!

**Comment by plmuninn** [comment]
Thx for information : ).
